apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: wildcard
spec:
  hostname: "*"
  acmeProvider:
    authority: none # Выключаем использование https
  requestPolicy:
    insecure:
      action: Route
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: user
spec:
  prefix: /user/
  service: user.user
  cors:
    origins: "*"
    methods: POST, GET, PUT, OPTIONS, HEAD
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: auth
spec:
  prefix: /auth/
  service: auth.auth
  bypass_auth: true # Отключаем аутентификацию на запросы к auth-service
  cors:
    origins: "*"
    methods: POST, GET, PUT, OPTIONS, HEAD
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: billing
spec:
  prefix: /billing/
  service: billing.billing
  cors:
    origins: "*"
    methods: POST, GET, PUT, OPTIONS, HEAD
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: order
spec:
  prefix: /order/
  service: order.order
  cors:
    origins: "*"
    methods: POST, GET, PUT, OPTIONS, HEAD
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: notification
spec:
  prefix: /notification/
  service: notification.notification
  cors:
    origins: "*"
    methods: POST, GET, PUT, OPTIONS, HEAD