apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  PORT_USER: "8888"
  PORT_AUTH: "9999"
  DB_DRIVER: "postgres"
  DB_HOST: postgres
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  DB_NAME: "bXlkYg=="
  DB_USER: "bXl1c2Vy"
  DB_PASSWORD: "bXlwYXNzd29yZA=="
  DB_SSLMODE: "ZGlzYWJsZQ=="
