apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  DB_DRIVER: postgres
  DB_HOST: postgres.postgres
  DB_PORT: "5432"
  BILLING_SERVICE: http://billing.billing
  RABBIT_HOST: my-rabbit-rabbitmq.rabbit.svc
  RABBIT_PORT: "5672"
  QUEUE_NAME: order_events
---
apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  DB_NAME: "bXlkYg=="
  DB_USER: "bXl1c2Vy"
  DB_PASSWORD: "bXlwYXNzd29yZA=="
  DB_SSLMODE: "ZGlzYWJsZQ=="
  RABBIT_USERNAME: "Z3Vlc3Q="
  RABBIT_PASSWORD: "Z3Vlc3Q="
