apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    app: user
  ports:
    - port: 80
      name: http
      targetPort: http
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:latest
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_PORT
          command:
            - sh
            - -c
            - until pg_isready --host=$POSTGRES_HOST --port=$POSTGRES_PORT; do sleep 1; done
      containers:
        - name: user
          image: murzayev/otu_stream_processing_user:latest
          ports:
            - name: http
              containerPort: 8888
          env:
            - name: PORT
              value: "8888"
            - name: BILLING_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: BILLING_SERVICE
            - name: DB_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_DRIVER
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_PASSWORD
            - name: DB_SSLMODE
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_SSLMODE
          livenessProbe:
            httpGet:
              port: 8888
              path: /health
            initialDelaySeconds: 3
            periodSeconds: 1
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8888
              path: /health
            initialDelaySeconds: 3
            periodSeconds: 1
            timeoutSeconds: 2